Script started on Sat 09 Dec 2017 12:49:15 AM PST
]0;lcai5@laguna:~/hw5[lcai5@laguna ~/hw5]$ dafsdf[K[K[K[K[K[Kmake all
gcc -ansi -Wall -c MovieLab.c -o MovieLab.o -lm #-lm is to link Math Library to use power function
gcc -ansi -Wall -c FileIO.c -o FileIO.o
gcc -ansi -Wall -c Image.c -o Image.o
gcc -ansi -Wall -c ImageList.c -o ImageList.o
gcc -ansi -Wall -c Movie.c -o Movie.o 
gcc -ansi -Wall -c  DIPs.c -o DIPs.o
ar rc libFilter.a DIPs.o
ranlib libFilter.a
gcc -ansi -Wall MovieLab.o FileIO.o Image.o ImageList.o Movie.o -L. -lFilter -o MovieLab  -lm 
]0;lcai5@laguna:~/hw5[lcai5@laguna ~/hw5]$ make all[23Gexit[Kcd hw5[23Gvalgrind ./MovieLab -i mouse.yuv -o out.yuv -s 480x270 -f 100 -zoom[82G46[K[23G[9P[72G80 -spotlight[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[Kh

Usage: MovieLab -i <file> -o <file> -f <framenum> -s <WIDTHxHEIGHT> [options]
Options:
-aging                Activate the aging filter on every movie frame
-hflip                Activate horizontal flip on every movie frame
-edge                 Activate the edge filter on every movie frame
-crop <start-end>     Crop the movie frames from <start> to <end>
-fast <factor>        Fast forward the movie by <factor>
-reverse              Reverse the frame order of the input movie
-watermark <file>     Add a watermark from <file> to every movie frame
-spotlight            Spotlight the fade in and fade out
-zoom                 Zoom in and out the input movie
-h                    Display this usage information
]0;lcai5@laguna:~/hw5[lcai5@laguna ~/hw5]$ ./MovieLab -h[23Gmake all[K[23Gexit[Kcd hw5[23Gvalgrind ./MovieLab -i mouse.yuv -o out.yuv -s 480x270 -f 100 -zoom[82G46[K[23G[9P[72G80 -spotlight[72G50 -watermark watermark.ppm[76Greverse[K[72G140 -fast 3 -crop 10-40[72G50 -aging -hflip[K[23Gscript[K[23G./MovieLab -i mouse.yuv -o out.yuv -s 480x270 -f 50 -aging -hflip
The movie file mouse.yuv was loaded successfully. 
"Aging" operation is done!
"HFlip" operation is done!
The movie file out.yuv has been written successfully!
50 frames are written to the file out.yuv in total.
The movie file out.yuv was saved successfully. 
]0;lcai5@laguna:~/hw5[lcai5@laguna ~/hw5]$ ./MovieLab -i mouse.yuv -o out.yuv -s 480x270 -f 50 -aging -hflip[35Gh[K[23Gmake all[K[23Gexit[Kcd hw5[23Gvalgrind ./MovieLab -i mouse.yuv -o out.yuv -s 480x270 -f 100 -zoom[82G46[K[23G[9P[72G80 -spotlight[72G50 -watermark watermark.ppm[76Greverse[K[72G140 -fast 3 -crop 10-40[23Gscript[K[23G./MovieLab -i mouse.yuv -o out.yuv -s 480x270 -f 140 -fast 3 -crop 10-40[23Gscript[K[23G./MovieLab -i mouse.yuv -o out.yuv -s 480x270 -f 140 -fast 3 -crop 10-40[72G50 -reverse[K[72G140 -fast 3 -crop 10-40[23Gscript[K[23G./MovieLab -i mouse.yuv -o out.yuv -s 480x270 -f 140 -fast 3 -crop 10-40[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K-edge
The movie file mouse.yuv was loaded successfully. 
"Edge" operation is done!
The movie file out.yuv has been written successfully!
140 frames are written to the file out.yuv in total.
The movie file out.yuv was saved successfully. 
]0;lcai5@laguna:~/hw5[lcai5@laguna ~/hw5]$ ./MovieLab -i mouse.yuv -o out.yuv -s 480x270 -f 140 -edge[72G50 -aging -hflip[35Gh[K[23Gmake all[K[23Gexit[Kcd hw5[23Gvalgrind ./MovieLab -i mouse.yuv -o out.yuv -s 480x270 -f 100 -zoom[82G46[K[23G[9P[72G80 -spotlight[72G50 -watermark watermark.ppm[76Greverse[K[72G140 -fast 3 -crop 10-40[P[P[P[1@1[1@5[1@0[P[P[1@4[1@0
The movie file mouse.yuv was loaded successfully. 
"Fast" operation is done!
New number of frames is 48 
"Crop" operation is done!
The movie file out.yuv has been written successfully!
31 frames are written to the file out.yuv in total.
The movie file out.yuv was saved successfully. 
]0;lcai5@laguna:~/hw5[lcai5@laguna ~/hw5]$ ./MovieLab -i mouse.yuv -o out.yuv -s 480x270 -f 140 -fast 3 -crop 10-40[77Gedge[K[72G50 -aging -hflip[35Gh[K[23Gmake all[K[23Gexit[Kcd hw5[23Gvalgrind ./MovieLab -i mouse.yuv -o out.yuv -s 480x270 -f 100 -zoom[82G46[K[23G[9P[72G80 -spotlight[72G50 -watermark watermark.ppm[76Greverse[K
The movie file mouse.yuv was loaded successfully. 
"Reverse" operation is done!
The movie file out.yuv has been written successfully!
50 frames are written to the file out.yuv in total.
The movie file out.yuv was saved successfully. 
]0;lcai5@laguna:~/hw5[lcai5@laguna ~/hw5]$ ./MovieLab -i mouse.yuv -o out.yuv -s 480x270 -f 50 -reverse[72G140 -fast 3 -crop 10-40[77Gedge[K[72G50 -aging -hflip[35Gh[K[23Gmake all[K[23Gexit[Kcd hw5[23Gvalgrind ./MovieLab -i mouse.yuv -o out.yuv -s 480x270 -f 100 -zoom[82G46[K[23G[9P[72G80 -spotlight[72G50 -watermark watermark.ppm
The movie file mouse.yuv was loaded successfully. 
"Watermark" operation is done!
The movie file out.yuv has been written successfully!
50 frames are written to the file out.yuv in total.
The movie file out.yuv was saved successfully. 
]0;lcai5@laguna:~/hw5[lcai5@laguna ~/hw5]$ ./MovieLab -i mouse.yuv -o out.yuv -s 480x270 -f 50 -watermark watermark.ppm[76Greverse[K[72G140 -fast 3 -crop 10-40[77Gedge[K[72G50 -aging -hflip[35Gh[K[23Gmake all[K[23Gexit[Kcd hw5[23Gvalgrind ./MovieLab -i mouse.yuv -o out.yuv -s 480x270 -f 100 -zoom[82G46[K[23G[9P[72G80 -spotlight
The movie file mouse.yuv was loaded successfully. 
"Spotlight" operation is done!
The movie file out.yuv has been written successfully!
80 frames are written to the file out.yuv in total.
The movie file out.yuv was saved successfully. 
]0;lcai5@laguna:~/hw5[lcai5@laguna ~/hw5]$ ./MovieLab -i mouse.yuv -o out.yuv -s 480x270 -f 80 -spotlight[72G50 -watermark watermark.ppm[76Greverse[K[72G140 -fast 3 -crop 10-40[77Gedge[K[72G50 -aging -hflip[35Gh[K[23Gmake all[K[23Gexit[Kcd hw5[23Gvalgrind ./MovieLab -i mouse.yuv -o out.yuv -s 480x270 -f 100 -zoom[82G46[K
==155787== Memcheck, a memory error detector
==155787== Copyright (C) 2002-2012, and GNU GPL'd, by Julian Seward et al.
==155787== Using Valgrind-3.8.1 and LibVEX; rerun with -h for copyright info
==155787== Command: ./MovieLab -i mouse.yuv -o out.yuv -s 480x270 -f 146
==155787== 
==155787== 
==155787== HEAP SUMMARY:
==155787==     in use at exit: 0 bytes in 0 blocks
==155787==   total heap usage: 0 allocs, 0 frees, 0 bytes allocated
==155787== 
==155787== All heap blocks were freed -- no leaks are possible
==155787== 
==155787== For counts of detected and suppressed errors, rerun with: -v
==155787== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 8 from 6)
]0;lcai5@laguna:~/hw5[lcai5@laguna ~/hw5]$ valgrind ./MovieLab -i mouse.yuv -o out.yuv -s 480x270 -f 146[23G[9P[72G80 -spotlight[72G50 -watermark watermark.ppm[76Greverse[K[72G140 -fast 3 -crop 10-40[77Gedge[K[72G50 -aging -hflip[35Gh[K[23Gmake all[K[23Gexit[Kcd hw5[23Gvalgrind ./MovieLab -i mouse.yuv -o out.yuv -s 480x270 -f 100 -zoom0[P[P[P[P[P[P[P[P[P
The movie file mouse.yuv was loaded successfully. 
"Zoom" operation is done!
The movie file out.yuv has been written successfully!
100 frames are written to the file out.yuv in total.
The movie file out.yuv was saved successfully. 
]0;lcai5@laguna:~/hw5[lcai5@laguna ~/hw5]$ c[Kmake clean
rm -f *.o  aging.yuv hflip.yuv edge.yuv crop.yuv fast.yuv reverse.yuv watermark.yuv spotlight.yuv zoom.yuv  libFilter.a libFileIO.a
]0;lcai5@laguna:~/hw5[lcai5@laguna ~/hw5]$ exit
exit

Script done on Sat 09 Dec 2017 12:52:36 AM PST
